# Generated by Django 4.0.2 on 2022-03-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_name_category_category_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_right',
            field=models.CharField(choices=[('C', 'C'), ('A', 'A'), ('B', 'B'), ('D', 'D')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='diffuculty',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
