# Generated by Django 4.0.2 on 2022-03-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_category_id_alter_answer_is_right_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_right',
            field=models.CharField(choices=[('C', 'C'), ('D', 'D'), ('A', 'A'), ('B', 'B')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='diffuculty',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
