# Generated by Django 4.0.2 on 2022-03-09 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_answer_choice1_remove_answer_choice2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
