# Generated by Django 4.0.2 on 2022-03-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quiz_options_rename_name_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='question',
            name='diffuculty',
            field=models.CharField(choices=[('M', 'Medium'), ('H', 'High'), ('L', 'Low')], max_length=50),
        ),
    ]
