# Generated by Django 4.0.2 on 2022-03-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_rename_title_question_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='question',
            name='diffuculty',
            field=models.CharField(choices=[('M', 'Medium'), ('H', 'High'), ('L', 'Low')], max_length=50),
        ),
    ]
