# Generated by Django 4.0.2 on 2022-03-10 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_rename_question_question_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='diffuculty',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
