# Generated by Django 4.0.2 on 2022-03-08 08:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_api.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category_id',
            field=models.IntegerField(),
        ),
    ]
