# Generated by Django 4.0.2 on 2022-03-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_quiz_quiz_alter_quiz_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
